Validations
jroodman/HackerNews pull request #2
Opened 2017-06-12 14:12 UTC by jroodman

This PR creates adds validations to the models for HackerNews. It also adds testing for these validations and all associations.

2017-06-12 14:27 UTC, h0tl33t commented on app/models/vote.rb
> +
I think you'll also want an application-level `uniqueness` validation here for the combination of `user_id`, `votable_id`, and `votable_type`.  Check out the bit on the `:scope` option in the [validation Rails docs](http://guides.rubyonrails.org/active_record_validations.html#uniqueness).

2017-06-12 14:28 UTC, h0tl33t commented on spec/models/vote_spec.rb
> +
After adding the uniqueness validation to the model, be sure to cover it with a test here as well.

2017-06-12 14:29 UTC, rysospicy approved these changes
Looks good!  There's one more validation to address, but otherwise :100:

2017-06-12 16:48 UTC, zporter commented on app/models/comment.rb
> +  belongs_to :parent, class_name: :Comment, foreign_key: :parent_comment_id
can a Comment also belong to a post / link?

2017-06-12 16:54 UTC, zporter commented on spec/models/comment_spec.rb
> +  it { should validate_presence_of :votes_count }
will `votes_count` eventually be a [counter cache](http://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-counter-cache)?

2017-06-12 16:56 UTC, zporter requested changes
Left a couple of comments to address. Ping me in Slack when you've addressed them so I can re-review.  Great work!

2017-06-12 22:29 UTC, jroodman commented on spec/models/comment_spec.rb
> +  it { should validate_presence_of :votes_count }
yup!

2017-06-12 22:42 UTC, jroodman commented on app/models/comment.rb
> +  belongs_to :parent, class_name: :Comment, foreign_key: :parent_comment_id
Yup, good catch. Thanks!

2017-06-12 22:49 UTC, jroodman commented on spec/models/comment_spec.rb
> +  it { should validate_presence_of :votes_count }
Good catch on that as well, put off implementing that earlier and forgot to add it in.

2017-06-13 12:41 UTC, zporter commented on spec/models/user_spec.rb
> +  it { should_not allow_value('username space').for(:username) }
add a test for a username with 1 number

2017-06-13 12:42 UTC, zporter approved these changes
nice work! Add one more test around a username with 1 number and receive a 👍

2017-06-13 16:18 UTC, merged